# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Firehouse < Formula
  desc ""
  homepage "https://github.com/izqalan/firehouse"
  version "0.5.6"

  on_macos do
    url "https://github.com/izqalan/firehouse/releases/download/v0.5.6/firehouse_0.5.6_darwin_all.tar.gz"
    sha256 "bb20cd993b3001b9324d744bc3d239ac538962579e9d5259e06cf351d474257c"

    def install
      bin.install "firehouse"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/izqalan/firehouse/releases/download/v0.5.6/firehouse_0.5.6_linux_amd64.tar.gz"
      sha256 "a2a6bd4a600052818c4dc9da665a77f9170a38bd1f9430aa069d257d492e849d"

      def install
        bin.install "firehouse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/izqalan/firehouse/releases/download/v0.5.6/firehouse_0.5.6_linux_arm64.tar.gz"
      sha256 "1208923cea9fdd6b8d2438e8dedbb9a76df112e9355c60e212ca579a938d15e3"

      def install
        bin.install "firehouse"
      end
    end
  end
end
