# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Firehouse < Formula
  desc ""
  homepage "https://github.com/izqalan/firehouse"
  version "0.5.15"

  on_macos do
    url "https://github.com/izqalan/firehouse/releases/download/v0.5.15/firehouse_0.5.15_darwin_all.tar.gz"
    sha256 "a3c21580a69fc2de08fdcd3d6e82d396adc1478f5c62bfa7cab60c4832aaafd0"

    def install
      bin.install "firehouse"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/izqalan/firehouse/releases/download/v0.5.15/firehouse_0.5.15_linux_arm64.tar.gz"
      sha256 "26128705a6c15666afce991b7c709c62fe1524716749fc6e75285c1b41cdc4ee"

      def install
        bin.install "firehouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/izqalan/firehouse/releases/download/v0.5.15/firehouse_0.5.15_linux_amd64.tar.gz"
      sha256 "bba5247d9a895ed690838c2a0f9eb9c6c2f0746ab60962a4527c316130588a6c"

      def install
        bin.install "firehouse"
      end
    end
  end
end
